apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rewards-non-prod-root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/aelbaz926/rewards-gitops.git
    targetRevision: HEAD
    path: clusters/non-prod
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
