apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: pt-login-appset
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          - name: pt-login
            environment: dev
          - name: pt-login
            environment: qa
          - name: pt-login
            environment: staging
  template:
    metadata:
      name: "{{.name}}-{{.environment}}"
    spec:
      project: default
      sources:
        - repoURL: https://github.com/aelbaz926/rewards-gitops.git
          targetRevision: HEAD
          path: helm-charts/common
          helm:
            valueFiles:
              - $values/environment-files/{{.environment}}/{{.name}}-values.yaml
        - repoURL: https://github.com/aelbaz926/rewards-gitops.git
          targetRevision: HEAD
          ref: values
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{.environment}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
